name: create a release from a tag
# this silliness exists because the web version of creating a release
# doesn't accept tags

on:
  workflow_dispatch:
    inputs:
      rel_tag:
        description: the name of the release tag
        type: string
      for_tag:
        description: the source tag to create the release from
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

    - name: set github-actions identity
      shell: bash
      run: |
        # this pair is magic: https://github.com/actions/checkout/tree/v4.2.2#push-a-commit-using-the-built-in-token
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: cook the release entity
      shell: bash
      # env:
      #  GH_TOKEN: ${{ github.token }}
      # 'gh release create' 403s with github.token which explains this nonsense
      run: |
        git fetch --tags
        tag_name="${{ inputs.for_tag }}"
        target_sha=$(git rev-parse ${tag_name})
        # :rolling_eyes:
        # hint: You have created a nested tag. The object referred to by your new tag is
        # hint: already a tag. If you meant to tag the object that it points to, use:
        # hint: 	git tag -f v3.1.0 7f6f2dc2aec61bcf9a31492d80d932253f62af81^{}
        git tag -f "-mRelease ${{ inputs.rel_tag }}" "${{ inputs.rel_tag }}" "${target_sha}^{}"
        git push --tags
