name: autobots, roll out

on:
  push:
    branches:
    # -> dev automagically
    - main
    # the other branches are covered under the "workflow_dispatch:"
    # and then picking the branch

concurrency:
  group: deploy-${{ github.sha }}
  cancel-in-progress: true

jobs:
  sniff-it:
    runs-on: ubuntu-latest
    name: dynamic information
    outputs:
      build_id: ${{ steps.stamp.outputs.the_build_id }}
      the_url: ${{ steps.the-url.outputs.the_url }}
    permissions:
      contents: write
    steps:
    - name: checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

    - name: stamp it
      id: stamp
      run: |
        if [[ "${{ runner.debug }}" -eq 1 ]]; then
          set -x
          echo "ACTIONS_RUNNER_DEBUG := <<${ACTIONS_RUNNER_DEBUG}>>" >&2
          echo "ACTIONS_STEP_DEBUG := <<${ACTIONS_STEP_DEBUG}>>" >&2
        fi

        # this pair is magic: https://github.com/actions/checkout/tree/v4.2.2#push-a-commit-using-the-built-in-token
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        my_tag=v0.${GITHUB_RUN_ID}.0
        # be aware markdown does not work here
        tag_msg="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
        git tag "-m$tag_msg" "$my_tag" HEAD
        git push origin tag  "$my_tag"
        echo "the_build_id=$my_tag" > $GITHUB_OUTPUT

    - name: discover url
      id: the-url
      run: echo "the_url=https://${{ github.ref_name }}.example.com" > $GITHUB_OUTPUT

  deploy-it:
    needs:
    - sniff-it
    runs-on: ubuntu-latest
    permissions: write-all
    name: deploy to ${{ github.ref_name }}
    environment:
      # we could obviously cook this in the prior job, too
      name: env/${{ (github.ref == 'refs/heads/main') && 'dev' || github.ref_name }}
      url: ${{ needs.sniff-it.outputs.the_url }}
    steps:
    - name: yeet it
      shell: bash
      env:
        EKS_ARN: ${{ vars.EKS_ARN }}
        # dumb
        GH_TOKEN: ${{ github.token }}
        THE_BUILD_ID: ${{ needs.sniff-it.outputs.build_id }}
      run: |
        echo "currently on ${{ runner.environment }} and sending ${THE_BUILD_ID} into ${EKS_ARN}"
        if ! gh api --verbose \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/mdaniel/repo1/deployments
        then
          echo "Welp, not like that I guess RC=${PIPESTATUS[0]}" >&2
        fi
