name: reviewdog.yaml
on:
  push:

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Install reviewdog
        shell: bash
        run: >-
          curl -fSL https://github.com/reviewdog/reviewdog/releases/download/v0.20.3/reviewdog_0.20.3_Linux_x86_64.tar.gz 
          | tar -xzf - -C /usr/local/bin reviewdog

      - name: Ensure pylint
        shell: bash
        run: |
          python3 -m venv /tmp/reviewdog-venv
          /tmp/reviewdog-venv/bin/pip install pylint

      - name: Run reviewdog
        shell: bash
        env:
           REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
        run: >-
          set -x;
          /tmp/reviewdog-venv/bin/pylint botocore
          | reviewdog -f=pylint -name="pylint"
          -log-level=debug
          -reporter=github-pr-check -level=info
        # -filter-mode=added
