name: example workflow
on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: mdaniel/repo0/actions/foo@main
        with:
          # language=yaml
          KUBECONFIG_YAML: |
            apiVersion: v1
            kind: Config
            clusters:
              - name: uh-huh
                cluster:
                  certificate-authority-data: yup
                  server: https://CAFEBABE.example
      - name: show the results
        run: |
          echo "the resulting KUBECONFIG is \"$KUBECONFIG\""
          ls -la $RUNNER_TEMP || true
          ps auwx | grep http.server || true
        shell: bash
